# Classification challenge!

1. Logistic Regression 
1. SVC
1. Decision Tree Classifier
1. RandomForestClassifier
1. KNeighborsClassifier
1. Gradient Boosting Classifier
1. "Neural Net": MLPClassifier
1. "Naive Bayes": GaussianNB(),
1. "AdaBoost": AdaBoostClassifier()**

In [1]:
# Logistic Regression 
# SVC
# Decision Tree Classifier
# RandomForestClassifier
# KNeighborsClassifier
# Gradient Boosting Classifier
# "Neural Net": MLPClassifier
# "Naive Bayes": GaussianNB(),
# "AdaBoost": AdaBoostClassifier(),

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Data
dataframe = pd.read_csv("../input/heart.csv")
dataframe.head()

age  sex  cp  trestbps  chol   ...    oldpeak  slope  ca  thal  target
0   63    1   3       145   233   ...        2.3      0   0     1       1
1   37    1   2       130   250   ...        3.5      0   0     2       1
2   41    0   1       130   204   ...        1.4      2   0     2       1
3   56    1   1       120   236   ...        0.8      2   0     2       1
4   57    0   0       120   354   ...        0.6      2   0     2       1

[5 rows x 14 columns]

In [4]:
dataframe.shape

(303, 14)

In [5]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.2 KB


In [6]:
dataframe.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# Test train split
from sklearn.model_selection import train_test_split

In [8]:
X = dataframe.iloc[:,:13]
y = dataframe['target']
X.head()
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [9]:
X.shape

(303, 13)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=40)

### Logistic Regression Implementation 

In [11]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

In [12]:
clf.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
predictions = clf.predict(X_test)

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [15]:
confusion_matrix(y_test, predictions)

array([[35,  5],
       [ 3, 48]])

In [16]:
accuracy_score(y_test, predictions)

0.9120879120879121

## SVC

In [17]:
from sklearn.svm import SVC

In [18]:
clf = SVC()

In [19]:
clf.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [20]:
predictions = clf.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [22]:
confusion_matrix(y_test, predictions)

array([[ 1, 39],
       [ 0, 51]])

In [23]:
accuracy_score(y_test, predictions)

0.5714285714285714

# Decision Tree Classifier

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
clf = DecisionTreeClassifier()

In [26]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [27]:
predictions = clf.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [29]:
confusion_matrix(y_test, predictions)

array([[31,  9],
       [13, 38]])

In [30]:
accuracy_score(y_test, predictions)

0.7582417582417582

## Random Forest Classifier

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
clf = RandomForestClassifier()

In [33]:
clf.fit(X_train, y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
predictions= clf.predict(X_test)

In [35]:
confusion_matrix(y_test, predictions)

array([[33,  7],
       [12, 39]])

In [36]:
accuracy_score(y_test, predictions)

0.7912087912087912

## Gradient Boot Classifier

In [37]:
from sklearn.ensemble import GradientBoostingClassifier

In [38]:
clf = GradientBoostingClassifier()

In [39]:
clf.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [40]:
predictions = clf.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
confusion_matrix(y_test, predictions)

array([[30, 10],
       [ 6, 45]])

In [43]:
accuracy_score(y_test, predictions)

0.8241758241758241

## KNeighbours Classifier

In [44]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
clf = KNeighborsClassifier()

In [46]:
clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [47]:
predictions = clf.predict(X_test)

In [48]:
confusion_matrix(y_test, predictions)

array([[25, 15],
       [13, 38]])

In [49]:
accuracy_score(y_test, predictions)

0.6923076923076923

## Gaussian NB (Naive Bayes)

In [50]:
from sklearn.naive_bayes import GaussianNB

In [51]:
clf = GaussianNB()

In [52]:
clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [53]:
predictions = clf.predict(X_test)

In [54]:
confusion_matrix(y_test, predictions)

array([[35,  5],
       [ 6, 45]])

In [55]:
accuracy_score(y_test, predictions)

0.8791208791208791

## Gussian Process Classifier

In [56]:
from sklearn.gaussian_process import GaussianProcessClassifier

In [57]:
clf = GaussianProcessClassifier()

In [58]:
clf.fit(X_train, y_train)

GaussianProcessClassifier(copy_X_train=True, kernel=None,
             max_iter_predict=100, multi_class='one_vs_rest', n_jobs=None,
             n_restarts_optimizer=0, optimizer='fmin_l_bfgs_b',
             random_state=None, warm_start=False)

In [59]:
predictions = clf.predict(X_test)

In [60]:
confusion_matrix(y_test, predictions)

array([[18, 22],
       [15, 36]])

In [61]:
accuracy_score(y_test, predictions)

0.5934065934065934

## AdaBoost Classifier

In [62]:
from sklearn.ensemble import AdaBoostClassifier

In [63]:
clf = AdaBoostClassifier()

In [64]:
clf.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [65]:
predictions = clf.predict(X_test)

In [66]:
confusion_matrix(y_test, predictions)

array([[32,  8],
       [10, 41]])

In [67]:
accuracy_score(y_test, predictions)

0.8021978021978022